-- MySQL Script generated by MySQL Workbench
-- Wed Apr 15 22:43:00 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pwa_opti
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pwa_opti
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pwa_opti` DEFAULT CHARACTER SET utf8 ;
USE `pwa_opti` ;

-- -----------------------------------------------------
-- Table `pwa_opti`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwa_opti`.`departamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pwa_opti`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwa_opti`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `id_dept` INT NOT NULL,
  `rol` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `depoartamento_usuarioo_idx` (`id_dept` ASC) ,
  CONSTRAINT `departamento_usuario`
    FOREIGN KEY (`id_dept`)
    REFERENCES `pwa_opti`.`departamentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pwa_opti`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwa_opti`.`personal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_completo` VARCHAR(150) NOT NULL,
  `id_dept` INT NOT NULL,
  `cedula` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `personal_departamento_idx` (`id_dept` ASC) ,
  CONSTRAINT `personal_departamento`
    FOREIGN KEY (`id_dept`)
    REFERENCES `pwa_opti`.`departamentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pwa_opti`.`roles_permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwa_opti`.`roles_permisos` (
  `id_rol` INT NULL,
  `id_permiso` INT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pwa_opti`.`logs_actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwa_opti`.`logs_actividad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `accion` TEXT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `ip` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `logs_usuario_idx` (`id_usuario` ASC) ,
  CONSTRAINT `logs_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `pwa_opti`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pwa_opti`.`metodos_levantamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwa_opti`.`metodos_levantamiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pwa_opti`.`estado_pozo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwa_opti`.`estado_pozo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pwa_opti`.`vdfs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwa_opti`.`vdfs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(50) NOT NULL,
  `capacidad` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pwa_opti`.`cabezales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwa_opti`.`cabezales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pwa_opti`.`pozos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwa_opti`.`pozos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(20) NOT NULL,
  `categoria` VARCHAR(10) NOT NULL,
  `id_estado` INT NOT NULL,
  `area` VARCHAR(50) NOT NULL,
  `yacimiento` VARCHAR(50) NULL,
  `potencial` DECIMAL(10,2) NULL,
  `latitud` DECIMAL(11,8) NULL,
  `longitud` DECIMAL(11,8) NULL,
  `id_vdf` INT NULL,
  `id_cabezal` INT NULL,
  `id_metodo` INT NULL,
  `fecha_arranque` DATE NULL,
  `vel_operacional` DECIMAL(10,2) NULL,
  `vel_actual` DECIMAL(10,2) NULL,
  `ays_pba` DECIMAL(5,2) NULL,
  `rgp_pba` DECIMAL(10,2) NULL,
  `api_pba` DECIMAL(5,2) NULL,
  `id_diagrama_principal` INT NULL,
  `last_sync_mapa` DATETIME NULL,
  `color_estado_mapa` VARCHAR(7) NULL,
  PRIMARY KEY (`id`),
  INDEX `pozo_estado_idx` (`id_estado` ASC) ,
  INDEX `pozo_cabezal_idx` (`id_cabezal` ASC) ,
  INDEX `pozo_vdf_idx` (`id_vdf` ASC) ,
  INDEX `pozo_metodo_idx` (`id_metodo` ASC) ,
  CONSTRAINT `pozo_estado`
    FOREIGN KEY (`id_estado`)
    REFERENCES `pwa_opti`.`estado_pozo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pozo_cabezal`
    FOREIGN KEY (`id_cabezal`)
    REFERENCES `pwa_opti`.`cabezales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pozo_vdf`
    FOREIGN KEY (`id_vdf`)
    REFERENCES `pwa_opti`.`vdfs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pozo_metodo`
    FOREIGN KEY (`id_metodo`)
    REFERENCES `pwa_opti`.`metodos_levantamiento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pwa_opti`.`bombas_historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwa_opti`.`bombas_historial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_pozo` INT NOT NULL,
  `marca` VARCHAR(50) NOT NULL,
  `modelo` VARCHAR(50) NOT NULL,
  `serial` VARCHAR(50) NULL,
  `fecha_inst` DATE NOT NULL,
  `fecha_falla` DATE NULL,
  `tvu` INT NULL,
  `estatus` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `pozo_bomba_idx` (`id_pozo` ASC) ,
  CONSTRAINT `pozo_bomba`
    FOREIGN KEY (`id_pozo`)
    REFERENCES `pwa_opti`.`pozos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pwa_opti`.`cabezal_historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwa_opti`.`cabezal_historial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_pozo` INT NOT NULL,
  `id_cabezal` INT NOT NULL,
  `fecha_inst` DATE NULL,
  `observaciones` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `cabezal_pozoh_idx` (`id_pozo` ASC) ,
  INDEX `historico_cabezal_idx` (`id_cabezal` ASC) ,
  CONSTRAINT `cabezal_pozoh`
    FOREIGN KEY (`id_pozo`)
    REFERENCES `pwa_opti`.`pozos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `historico_cabezal`
    FOREIGN KEY (`id_cabezal`)
    REFERENCES `pwa_opti`.`cabezales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pwa_opti`.`completacion_detalles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwa_opti`.`completacion_detalles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_pozo` INT NOT NULL,
  `tipo_elemento` VARCHAR(50) NULL,
  `diametro` VARCHAR(20) NULL,
  `modelo` VARCHAR(50) NULL,
  `longitud` DECIMAL(10,2) NULL,
  `cantidad` INT NULL,
  `orden_sarta` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `pozo_completacion_idx` (`id_pozo` ASC) ,
  CONSTRAINT `pozo_completacion`
    FOREIGN KEY (`id_pozo`)
    REFERENCES `pwa_opti`.`pozos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pwa_opti`.`pozos_survey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwa_opti`.`pozos_survey` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_pozo` INT NOT NULL,
  `md` DECIMAL NULL,
  `tvd` DECIMAL NULL,
  `inc` DECIMAL NULL,
  `azi` DECIMAL NULL,
  PRIMARY KEY (`id`),
  INDEX `survey_pozo_idx` (`id_pozo` ASC) ,
  CONSTRAINT `survey_pozo`
    FOREIGN KEY (`id_pozo`)
    REFERENCES `pwa_opti`.`pozos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pwa_opti`.`documentacion_pozo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwa_opti`.`documentacion_pozo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_pozo` INT NOT NULL,
  `tipo_doc` VARCHAR(50) NULL,
  `url_archivo` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `docu_pozo_idx` (`id_pozo` ASC) ,
  CONSTRAINT `docu_pozo`
    FOREIGN KEY (`id_pozo`)
    REFERENCES `pwa_opti`.`pozos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pwa_opti`.`parametros_diarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwa_opti`.`parametros_diarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid_local` VARCHAR(36) NOT NULL,
  `id_pozo` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `torque` DECIMAL NULL,
  `amp` DECIMAL NULL,
  `freq` DECIMAL NULL,
  `volts` DECIMAL NULL,
  `rpm` DECIMAL NULL,
  `hp` DECIMAL NULL,
  `sync_status` TINYINT(1) NULL,
  `id_personal` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `parametros_pozo_idx` (`id_pozo` ASC) ,
  INDEX `parametros_personal_idx` (`id_personal` ASC) ,
  CONSTRAINT `parametros_pozo`
    FOREIGN KEY (`id_pozo`)
    REFERENCES `pwa_opti`.`pozos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `parametros_personal`
    FOREIGN KEY (`id_personal`)
    REFERENCES `pwa_opti`.`personal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pwa_opti`.`muestras_fluido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwa_opti`.`muestras_fluido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_pozo` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `ays` DECIMAL(5,2) NOT NULL,
  `api` DECIMAL(5,2) NOT NULL,
  `representativa` TINYINT NULL,
  `prox_muestra` DATE NOT NULL,
  `sync_status` TINYINT(1) NOT NULL,
  `id_personal` INT NULL,
  `uuid_local` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `muestra_pozo_idx` (`id_pozo` ASC) ,
  INDEX `muestra_personal_idx` (`id_personal` ASC) ,
  CONSTRAINT `muestra_pozo`
    FOREIGN KEY (`id_pozo`)
    REFERENCES `pwa_opti`.`pozos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `muestra_personal`
    FOREIGN KEY (`id_personal`)
    REFERENCES `pwa_opti`.`personal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pwa_opti`.`muestras_seleccionadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwa_opti`.`muestras_seleccionadas` (
  `id_pozo` INT NOT NULL,
  `id_muestra` INT NOT NULL,
  INDEX `muestrasec_pozo_idx` (`id_pozo` ASC) ,
  INDEX `muestrasec_muestra_idx` (`id_muestra` ASC) ,
  CONSTRAINT `muestrasec_pozo`
    FOREIGN KEY (`id_pozo`)
    REFERENCES `pwa_opti`.`pozos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `muestrasec_muestra`
    FOREIGN KEY (`id_muestra`)
    REFERENCES `pwa_opti`.`muestras_fluido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pwa_opti`.`tomas_nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwa_opti`.`tomas_nivel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_pozo` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `nf_pies` DECIMAL NOT NULL,
  `sumergencia` DECIMAL NOT NULL,
  `pip` DECIMAL NOT NULL,
  `pbhp` DECIMAL NOT NULL,
  `presion_casing` DECIMAL NOT NULL,
  `diagnostico` TEXT NULL,
  `recomendacion` TEXT NULL,
  `sync_status` TINYINT(1) NOT NULL,
  `id_personal` INT NULL,
  `uuid_local` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `nivel_pozo_idx` (`id_pozo` ASC) ,
  INDEX `nivel_personal_idx` (`id_personal` ASC) ,
  CONSTRAINT `nivel_pozo`
    FOREIGN KEY (`id_pozo`)
    REFERENCES `pwa_opti`.`pozos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `nivel_personal`
    FOREIGN KEY (`id_personal`)
    REFERENCES `pwa_opti`.`personal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pwa_opti`.`cola_sincronizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwa_opti`.`cola_sincronizacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tabla_afectada` VARCHAR(50) NULL,
  `id_registro_local` VARCHAR(36) NULL,
  `accion` VARCHAR(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pwa_opti`.`alertas_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwa_opti`.`alertas_config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_alerta` VARCHAR(50) NULL,
  `dias_vencimiento` INT NULL,
  `color_hex` VARCHAR(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pwa_opti`.`unidades_servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwa_opti`.`unidades_servicio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `tipo_unidad` VARCHAR(45) NOT NULL,
  `empresa_servicio` VARCHAR(100) NOT NULL,
  `estatus` VARCHAR(50) NULL,
  `lat_actual` DECIMAL(11,8) NOT NULL,
  `lng_actual` DECIMAL(11,8) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pwa_opti`.`servicios_programados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwa_opti`.`servicios_programados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_pozo` INT NOT NULL,
  `id_unidad` INT NOT NULL,
  `tipo_servicio` VARCHAR(50) NOT NULL,
  `fecha_est` DATE NULL,
  `prioridad` INT NOT NULL,
  `estatus_prog` VARCHAR(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `servicio_pozo_idx` (`id_pozo` ASC) ,
  INDEX `servicio_unidad_idx` (`id_unidad` ASC) ,
  CONSTRAINT `servicio_pozo`
    FOREIGN KEY (`id_pozo`)
    REFERENCES `pwa_opti`.`pozos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `servicio_unidad`
    FOREIGN KEY (`id_unidad`)
    REFERENCES `pwa_opti`.`unidades_servicio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pwa_opti`.`eventos_intervencionales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwa_opti`.`eventos_intervencionales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_pozo` INT NOT NULL,
  `id_unidad` INT NOT NULL,
  `fecha_entrada` DATE NOT NULL,
  `fecha_salida` DATE NOT NULL,
  `actividad` TEXT NOT NULL,
  `hallazgos` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `evento_unidad_idx` (`id_unidad` ASC) ,
  INDEX `evento_pozo_idx` (`id_pozo` ASC) ,
  CONSTRAINT `evento_unidad`
    FOREIGN KEY (`id_unidad`)
    REFERENCES `pwa_opti`.`unidades_servicio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `evento_pozo`
    FOREIGN KEY (`id_pozo`)
    REFERENCES `pwa_opti`.`pozos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pwa_opti`.`diagramas_maestros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwa_opti`.`diagramas_maestros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `url_imagen_base` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pwa_opti`.`pozos_layout_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pwa_opti`.`pozos_layout_config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_pozo` INT NOT NULL,
  `id_diagrama` INT NOT NULL,
  `posicion_x` DECIMAL(10,2) NOT NULL,
  `posicion_y` DECIMAL(10,2) NOT NULL,
  `angulo_rotacion` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `layout_pozo_idx` (`id_pozo` ASC) ,
  INDEX `layout_diagrama_idx` (`id_diagrama` ASC) ,
  CONSTRAINT `layout_pozo`
    FOREIGN KEY (`id_pozo`)
    REFERENCES `pwa_opti`.`pozos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `layout_diagrama`
    FOREIGN KEY (`id_diagrama`)
    REFERENCES `pwa_opti`.`diagramas_maestros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
